command_timeout = 4000

[nodejs]
format = "via [$symbol($version )]($style)"
symbol = ' '

[c]
format = "via [$symbol($version )]($style)"
symbol = ' '

[elixir]
format = "via [$symbol($version )](purple bold)"
symbol = " "

[python]
format = "via [$symbol($version)](green bold)"
symbol = " "

[golang]
format = "via [$symbol($version )](blue bold)"
symbol = " "

[rust]
format = "via [$symbol($version )](red bold)"
symbol = "󱘗 "

[lua]
format = "via [$symbol($version )](blue bold)"
symbol = "󰢱 "

[php]
format = "via [$symbol($version )]($style)"
symbol = " "

[java]
format = "via [$symbol($version )](red bold)"
symbol = "☕ "

[docker_context]
format = 'via [$symbol($context)](blue bold)'
symbol = " "

[dart]
format = 'via [🔰$version](bold red) '

[ruby]
format = "via [$symbol($version )]($style)"
symbol = " "

[cmake]
format = "via [$symbol($version )]($style)"
symbol = "△ "

[zig]
format = "via [$symbol($version )]($style)"
# symbol = '⚡️'


# [sudo]
# style = 'bold green'
# symbol = '🤵 '
# disabled = false


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
