require("lazy-config")
require("settings")
require("mappings")

-- Color Schemess
-- require("colors.onedark")
require("colors.tokyonight")

require("nvim-tree-config")
require("mason-config")
require("lsp-config.language-servers")
require("lsp-config.nvim-cmp")
require("lualine-config")
require("barbar-config")
require("nvim-highlight-colors-config")
require("nvim-treesitter-config")
--require("mini-animate")
require("lsp-config.formatter")
require("transparent-config")
require("toggleterm-config")
-- require("telescope-config")
-- require("dashboard-config")
require("indentline-config")
-- require("nvim-jdtls-config")
require("gitsigns-config")
-- require("nvim-comment-config")
require("numToStr-comment-config")
require("lsp-config.nvim-metals-config")
-- require("dadbod-config") -- Database
